---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME_SERVICE
spec:
  selector:
    matchLabels:
      app: $NAME_SERVICE
  replicas: 2
  template:
    metadata:
      labels:
        app: $NAME_SERVICE
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: $NAME_SERVICE
          image: $IMAGE
          imagePullPolicy: "Always"
          ports:
          - containerPort: 3000
          envFrom:
            - secretRef:
                name: $NAME_SERVICE
          resources:
            limits:
              cpu: 1500m
              memory: "2Gi"
            requests:
              cpu: 500m
              memory: "512Mi"

--- 

kind: Service
apiVersion: v1
metadata:
  name: $NAME_SERVICE
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: $NAME_SERVICE
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: $NAME_SERVICE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $NAME_SERVICE
  minReplicas: 2
  maxReplicas: 5  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
