import {
  ROUTES_PROFILE,
  ROUTES_TRANSACTION,
  ROUTES_USER,
} from '@/src/constants';
import {
  DashboardIcon,
  MedevoIcon,
  ServiceIcon,
  TransactionIcon,
  UserIcon,
} from '@/assets/images/svg/menu';

const routeDashboard = [
  {
    title: 'Dashboard',
    name: 'dashboard',
    parent: '',
    subParent: '',
    routes: '/',
    icon: DashboardIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
];

const routeService = [
  {
    title: 'Layanan',
    name: 'layanan',
    parent: '',
    subParent: '',
    routes: '#',
    icon: ServiceIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
  {
    title: 'Registrasi',
    name: 'queue',
    parent: 'layanan',
    subParent: '',
    routes: `${ROUTES_TRANSACTION.QUEUE}`,
    icon: ServiceIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
  {
    title: 'Pendaftaran Pasien',
    name: 'register',
    parent: 'layanan',
    subParent: 'Registrasi',
    routes: `${ROUTES_TRANSACTION.REGISTER}/:id`,
    icon: ServiceIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
  {
    title: 'Klinik/Rawat Jalan',
    name: 'clinic-outpatients',
    parent: 'layanan',
    subParent: '',
    routes: `${ROUTES_TRANSACTION.CLINIC_OUTPATIENT}`,
    icon: ServiceIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
  {
    title: 'Pemeriksaan Pasien',
    name: 'clinic-outpatient-examination',
    parent: 'layanan',
    subParent: 'Klinik/Rawat Jalan',
    routes: `${ROUTES_TRANSACTION.CLINIC_OUTPATIENT_EXAMINATION}/:id`,
    icon: ServiceIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
  {
    title: 'Tindakan Medis',
    name: 'clinic-outpatient-treatment',
    parent: 'layanan',
    subParent: 'Klinik/Rawat Jalan',
    routes: `${ROUTES_TRANSACTION.CLINIC_OUTPATIENT_TREATMENT}/:id`,
    icon: ServiceIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
  {
    title: 'Imunisasi',
    name: 'Vaccinations',
    parent: 'layanan',
    subParent: '',
    routes: `${ROUTES_TRANSACTION.VACCINATIONS}`,
    icon: ServiceIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
  {
    title: 'Detail',
    name: 'Vaccination',
    parent: 'layanan',
    subParent: 'Imunisasi',
    routes: `${ROUTES_TRANSACTION.VACCINATION}/:id`,
    icon: ServiceIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
  {
    title: 'Pemeriksaan Pasien',
    name: 'Vaccination-checkup',
    parent: 'layanan',
    subParent: 'Imunisasi',
    routes: `${ROUTES_TRANSACTION.VACCINATION_CHECKUP}/:id`,
    icon: ServiceIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
  {
    title: 'Tindakan Medis',
    name: 'Vaccination-procedure',
    parent: 'layanan',
    subParent: 'Imunisasi',
    routes: `${ROUTES_TRANSACTION.VACCINATION_PROCEDURE}/:id`,
    icon: ServiceIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
  {
    title: 'Laboratorium',
    name: 'Laboratoriums',
    parent: 'layanan',
    subParent: '',
    routes: `${ROUTES_TRANSACTION.LABORATORIUMS}`,
    icon: ServiceIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
];

const routePengguna = [
  {
    title: 'Pengguna',
    name: 'pengguna',
    parent: '',
    subParent: '',
    routes: '#',
    icon: UserIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
  {
    title: 'Data Pasien',
    name: 'patients',
    parent: 'pengguna',
    subParent: '',
    routes: `${ROUTES_USER.DATA_USER}`,
    icon: UserIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
  {
    title: 'Detail Pasien',
    name: 'detail-patient',
    parent: 'pengguna',
    subParent: 'Data Pasien',
    routes: `${ROUTES_USER.DATA_USER_DETAIL}/:id`,
    icon: UserIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
];

const routeTransaction = [
  {
    title: 'Transaksi',
    name: 'transaksi',
    parent: '',
    subParent: '',
    routes: '#',
    icon: TransactionIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },

  {
    title: 'Pembayaran',
    name: 'payment',
    parent: 'transaksi',
    subParent: '',
    routes: `${ROUTES_TRANSACTION.PAYMENT}`,
    icon: TransactionIcon,
    exactPath: true,
    active: true,
    isAuthenticated: true,
  },
  {
    title: 'Detail',
    name: 'detail-payment',
    parent: 'transaksi',
    subParent: 'Pembayaran',
    routes: `${ROUTES_TRANSACTION.PAYMENT}/:id`,
    icon: TransactionIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
];

const routeProfile = [
  {
    title: 'Profile',
    name: 'profile',
    parent: '',
    subParent: '',
    routes: '#',
    icon: MedevoIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
  {
    title: 'Profile User',
    name: 'profile-user',
    parent: 'profile',
    subParent: '',
    routes: ROUTES_PROFILE.PROFILE_USER,
    icon: MedevoIcon,
    exactPath: true,
    active: false,
    isAuthenticated: true,
  },
];

const sidebarMenus = [
  ...routeDashboard,
  ...routeService,
  ...routePengguna,
  ...routeTransaction,
  ...routeProfile,
];

export default sidebarMenus;
