export type ReservationItemData = {
  id: string,
  createdAt: number,
  updatedAt: string,
  deletedAt: string,
  reservationDate: string,
  reservationTime: string,
  treatmentTypeID: number,
  outletId: number,
  source: string,
  outletType: string,
  treatmentMode: string,
  doctorID: number,
  participants: ReservationParticipantsData[],
  prescriptions: ReservationPrescriptionsData[],
  status: string,
  treatment: {
    name: string,
    type: string,
  },
  poly: {
    name: string,
  }
}

export type ReservationParticipantsData = {
  id: string,
  reservationId: number,
  reservation: string,
  createdAt: number,
  updatedAt: number,
  deletedAt: string,
  participantType: string,
  ektpUrl: string,
  userID: string,
  idpID: string,
  fullName: string,
  citizenshipId: string,
  birthPlace: string,
  birthDate: string,
  gender: string,
  maritalStatusId: number,
  address: string,
  citizenshipType: string,
  email: string,
  phoneNumber: string,
  passportNumber: string,
  isSelfRegister: boolean,
  familyRelationshipType: string,
  bpjsNumber: string,
  jobId: number,
  membershipType: string,
  feeId: number,
  contributionId: number,
  cityId: number,
  provinceId: number,
  selectedDate: string,
}

export type ReservationPrescriptionsData = {
  id: number,
  reservationId: number,
  reservation: string,
  createdAt: number,
  updatedAt: number,
  deletedAt: string,
  itemPrimaryTag: string,
  itemName: string,
  usageDescription: string,
  dosage: string;
}

export type ReservationDiagnosticData = {
  id: number,
  reservationId: number,
  createdAt: number,
  deletedAt: number,
  updatedAt: number,
  bloodPressure: string,
  bodyTemperature: string,
  initialDiagnose: string,
  object: string,
  patientComplain: string,
  patientHeight: string,
  patientWeight: string,
  subject: string,
}

export type ReservationMedicalSupportData = {
  id: number,
  reservationId: number,
  createdAt: number,
  deletedAt: number,
  updatedAt: number,
  attachmentUrl: string,
  description: string,
}

export type ReservationHospitalReferralData = {
  id: number,
  reservationId: number,
  createdAt: number,
  deletedAt: number,
  updatedAt: number,
  attachmentUrl: string,
  doctorID: number,
  doctorName: string,
  faskesID: number,
  faskesName: string,
  polyID: number,
  polyName: string,
}

export type Reference = {
  health_facility: string,
  poli: string,
  doctor: string,
  attachment: string,
}

export type DoctorPostData = {
  nama: string,
  tempatLahir: string,
  tanggalLahir: string,
  telepon: string,
  email: string,
  spesialis: string,
  foto: string,
  noStrDokter: string,
  fotoStr: string,
  fotoSip: string,
  sex: string,
  biografi: string,
  bahasa: string[],
};

export type UserHealthProfileData = {
  full_name: string,
  phone_number: string,
  email: string,
  user_id: string,
  idp_sub: string,
  profile_photo: string,
  birth_date: string,
  gender: string,
  ktp_no: string,
  study: string,
  no_emergency: string,
  ktp_photo: string,
  religion: string,
  health_profile_users_id: string,
  height: string,
  waist_size: string,
  bmi: number,
  weight: string,
  blood_type: string,
  allergy: string[],
  medicine_allergy: string[],
  diagnosis_treatment: string,
  comorbid: string,
  surgery_history: string,
  personal_medical_history: string,
  family_medical_history: [],
  smoking_option: string,
  smoking_amount: string,
  last_smoking: [],
  alcohol_consume: string,
  alcohol_amount: [],
  is_deleted: boolean,
}
