import {
  PAYMENT_STATUS_RESPONSE,
  REFUND_STATUS,
  REFUND_STATUS_RESPONSE,
  TRANSACTION_STATUS,
  TRANSACTION_STATUS_RESPONSE,
} from '@/src/constants';

export const orderStatus = (text: string, type?: string) => {
  switch (text) {
    case TRANSACTION_STATUS_RESPONSE.PENDING:
      return 'bg-[#FFE2E5] text-[#E5000C]';
    case TRANSACTION_STATUS_RESPONSE.SETTLEMENT:
      switch (type) {
        case 'medpoint':
          return 'bg-[#F7931E] text-white';
        case 'transaction':
          return 'bg-[#C8FFE4] text-[#00A854]';
        default:
          return 'bg-[#FFEECF] text-[#D48E0B]';
      }
    case TRANSACTION_STATUS_RESPONSE.COMPLETED:
    case PAYMENT_STATUS_RESPONSE.COMPLETED:
    case TRANSACTION_STATUS_RESPONSE.FINISHED:
    case TRANSACTION_STATUS_RESPONSE.CONFIRMED:
    case REFUND_STATUS_RESPONSE.REFUND_COMPLETED:
      return 'bg-[#48AA44] text-white';
    case TRANSACTION_STATUS_RESPONSE.FAILED:
    case TRANSACTION_STATUS_RESPONSE.CANCELLED:
    case TRANSACTION_STATUS_RESPONSE.CANCEL:
    case TRANSACTION_STATUS_RESPONSE.COMPLAINT_REJECTED:
      return 'bg-[#FF555F] text-white';
    case TRANSACTION_STATUS_RESPONSE.IN_PROGRESS:
      switch (type) {
        case 'transaction':
          return 'bg-[#1571FB] text-[#D1F7F5]';
        default:
          return 'bg-[#EFE2FF] text-[#9747FF]';
      }
    case TRANSACTION_STATUS_RESPONSE.IN_DELIVERY:
      return 'bg-[#194689] text-[#FFFFFF]';
    case TRANSACTION_STATUS_RESPONSE.READY_PICKING_UP:
      return 'bg-[#1571FB] text-[#D1F7F5]';
    case TRANSACTION_STATUS_RESPONSE.ORDER_ACCEPTED:
      return 'bg-[#C8FFE4] text-[#00A854]';
    case TRANSACTION_STATUS_RESPONSE.COMPLAINT_REQUESTED:
      return 'bg-[#FADEFF] text-[#DC08FF]';
    case TRANSACTION_STATUS_RESPONSE.COMPLAINT_ACCEPTED:
      return 'bg-[#039855] text-white';
    case TRANSACTION_STATUS_RESPONSE.COMPLAINT_APPROVED:
      return 'bg-[#00CC66] text-white';
    case TRANSACTION_STATUS_RESPONSE.WAITING_ROOM:
    case TRANSACTION_STATUS_RESPONSE.QUEUE:
    case PAYMENT_STATUS_RESPONSE.DRAFT:
      return 'bg-[#5A9CFF]/10 text-[#68A5FF]';
    case REFUND_STATUS_RESPONSE.REFUND_REQUEST:
      return 'bg-[#FADEFF] text-[#DC08FF]';
    case TRANSACTION_STATUS_RESPONSE.EXPIRE:
      return 'bg-[#FF555F] text-white';
    case REFUND_STATUS_RESPONSE.REFUND_PROCESSED:
      return 'bg-[#EFE2FF] text-[#9747FF]';
    case TRANSACTION_STATUS_RESPONSE.NEED_CONFIRMATION:
      return 'bg-[#D1F7F5] text-[#2B8EE0]';
    case TRANSACTION_STATUS_RESPONSE.ADMIN_CONFIRMATION:
      return 'bg-[#C7AAF7] text-[#4800C1]';
    case TRANSACTION_STATUS_RESPONSE.SYSTEM_CONFIRMATION:
    case TRANSACTION_STATUS_RESPONSE.IN_PROGRESS_PRESCRIPTION:
      return 'bg-[#FFEECF] text-[#D48E0B]';
    case TRANSACTION_STATUS_RESPONSE.NEW:
      return 'bg-[#D48E0B] text-[#FFEECF]';
    case TRANSACTION_STATUS_RESPONSE.REJECTED:
      return 'bg-[#FF555F] text-white';
    case TRANSACTION_STATUS_RESPONSE.PICKING_UP:
      switch (type) {
        case 'transaction':
          return 'bg-[#1571FB] text-[#D1F7F5]';
        default:
          return 'bg-[#C8FFE4] text-[#00A854]';
      }
    case TRANSACTION_STATUS_RESPONSE.WAITING_ACTION:
      return 'bg-[#C8FFE4] text-[#00A854]';
    case TRANSACTION_STATUS_RESPONSE.EXAMINED:
      return 'bg-[#48AA44] text-[#DDFFDC]';
    case TRANSACTION_STATUS_RESPONSE.REGISTER:
      return 'bg-primary text-[#FFFFFF]';
    case TRANSACTION_STATUS_RESPONSE.UNPAID:
    case PAYMENT_STATUS_RESPONSE.CANCELLED:
      return 'bg-[#9C0000] text-[#E0E0E0]';
    default:
      return '';
  }
};

export const orderStatusText = (text: string, type?: string) => {
  switch (text) {
    case TRANSACTION_STATUS_RESPONSE.PENDING:
      return TRANSACTION_STATUS.WAITING_FOR_PAYMENT;
    case TRANSACTION_STATUS_RESPONSE.SETTLEMENT:
      switch (type) {
        case 'medevo':
          return TRANSACTION_STATUS.FILL_COMPLAINT_FORM;
        case 'medpoint':
          return TRANSACTION_STATUS.SCHEDULED;
        case 'prescription':
          return TRANSACTION_STATUS.ORDER_ACCEPTED;
        case 'e-prescription':
          return 'Siapkan Resep';
        default:
          return TRANSACTION_STATUS.WAITING_FOR_CONFIRMATION;
      }
    case TRANSACTION_STATUS_RESPONSE.SETTLEMENT_PRESCRIPTION:
      return TRANSACTION_STATUS.ORDER_ACCEPTED;
    case TRANSACTION_STATUS_RESPONSE.IN_PROGRESS:
      return TRANSACTION_STATUS.IN_PROGRESS;
    case TRANSACTION_STATUS_RESPONSE.IN_PROGRESS_PRESCRIPTION:
      return TRANSACTION_STATUS.WAITING_FOR_CONFIRMATION;
    case TRANSACTION_STATUS_RESPONSE.IN_DELIVERY:
      return TRANSACTION_STATUS.IN_DELIVERY;
    case TRANSACTION_STATUS_RESPONSE.READY_PICKING_UP:
      return TRANSACTION_STATUS.READY_PICKING_UP;
    case TRANSACTION_STATUS_RESPONSE.PICKING_UP:
      return TRANSACTION_STATUS.PICKING_UP;
    case TRANSACTION_STATUS_RESPONSE.ORDER_ACCEPTED:
      return TRANSACTION_STATUS.ORDER_ACCEPTED;
    case TRANSACTION_STATUS_RESPONSE.COMPLETED:
      return TRANSACTION_STATUS.COMPLETED;
    case TRANSACTION_STATUS_RESPONSE.FAILED:
    case TRANSACTION_STATUS_RESPONSE.CANCELLED:
    case TRANSACTION_STATUS_RESPONSE.CANCEL:
      return TRANSACTION_STATUS.FAILED;
    case TRANSACTION_STATUS_RESPONSE.CONFIRMED:
      return TRANSACTION_STATUS.CONFIRMED;
    case TRANSACTION_STATUS_RESPONSE.COMPLAINT_REQUESTED:
      return TRANSACTION_STATUS.COMPLAINT_REQUESTED;
    case TRANSACTION_STATUS_RESPONSE.COMPLAINT_ACCEPTED:
      return TRANSACTION_STATUS.COMPLAINT_ACCEPTED;
    case TRANSACTION_STATUS_RESPONSE.COMPLAINT_APPROVED:
      return TRANSACTION_STATUS.COMPLAINT_APPROVED;
    case TRANSACTION_STATUS_RESPONSE.COMPLAINT_REJECTED:
      return TRANSACTION_STATUS.COMPLAINT_REJECTED;
    case TRANSACTION_STATUS_RESPONSE.WAITING_ROOM:
      return TRANSACTION_STATUS.WAITING_ROOM_CONSULTATION;
    case TRANSACTION_STATUS_RESPONSE.EXPIRE:
      return TRANSACTION_STATUS.EXPIRE;
    case REFUND_STATUS_RESPONSE.REFUND_PROCESSED:
      return REFUND_STATUS.REFUND_PROCESSED;
    case REFUND_STATUS_RESPONSE.REFUND_REQUEST:
      return REFUND_STATUS.NEED_TO_BE_PROCESSED;
    case REFUND_STATUS_RESPONSE.REFUND_COMPLETED:
      return REFUND_STATUS.REFUND_ACCEPTED;
    case TRANSACTION_STATUS_RESPONSE.NEED_CONFIRMATION:
    case TRANSACTION_STATUS_RESPONSE.SYSTEM_CONFIRMATION:
      return TRANSACTION_STATUS.NEED_CONFIRMATION;
    case TRANSACTION_STATUS_RESPONSE.ADMIN_CONFIRMATION:
      return TRANSACTION_STATUS.PRESCRIPTION_CONFIRMATION;
    case TRANSACTION_STATUS_RESPONSE.NEW:
      return TRANSACTION_STATUS.NEW;
    case TRANSACTION_STATUS_RESPONSE.REJECTED:
      return TRANSACTION_STATUS.EPRES_REJECTED;
    case TRANSACTION_STATUS_RESPONSE.FAILED_BY_OPERATOR:
      return TRANSACTION_STATUS.FAILED;
    case TRANSACTION_STATUS_RESPONSE.CANCEL_BY_SENDER:
      return TRANSACTION_STATUS.FAILED;
    case TRANSACTION_STATUS_RESPONSE.COMPLETED_EPRESCRIPTION:
      return TRANSACTION_STATUS.COMPLETED_EPRESCRIPTION;
    case TRANSACTION_STATUS_RESPONSE.QUEUE:
      return TRANSACTION_STATUS.QUEUE;
    case TRANSACTION_STATUS_RESPONSE.WAITING_ACTION:
      return TRANSACTION_STATUS.WAITING_ACTION;
    case TRANSACTION_STATUS_RESPONSE.EXAMINED:
      return TRANSACTION_STATUS.EXAMINED;
    case TRANSACTION_STATUS_RESPONSE.FINISHED:
      return TRANSACTION_STATUS.FINISHED;
    case TRANSACTION_STATUS_RESPONSE.REGISTER:
      return TRANSACTION_STATUS.REGISTER;
    case TRANSACTION_STATUS_RESPONSE.UNPAID:
      return TRANSACTION_STATUS.UNPAID;
    case 'new_chat':
      return 'Chat';
    default:
      return text;
  }
};
