export type ICashbackState = {
  cashbacks: {
    data: any,
    isError: boolean,
    isLoading: boolean,
    isSuccess: boolean,
    errorMessage: string,
    metadata: {
      page: number,
      limit: number,
      totalData: number,
      totalPage: number,
    },
  },
  cashback: {
    data: any,
    isError: boolean,
    isLoading: boolean,
    isSuccess: boolean,
    errorMessage: string,
  },
  cashbackById: {
    data: any,
    isError: boolean,
    isLoading: boolean,
    isSuccess: boolean,
    errorMessage: string,
  },
  formCashback: {
    isOpen: boolean,
    isOpenShowCoupon: boolean,
    isLoading: boolean,
    isSuccess: boolean,
    isError: boolean,
    errorMessage: string,
    successMessage: string,
    form: {
      name: string,
      title: string,
      description: string,
      code: string,
      type: string,
      quota: string,
      photo: string,
      target: string,
      nominal: string,
      percentage: string,
      endPeriod: string,
      startPeriod: string,
      maxDiscount: string,
      minPurchase: string,
      cashbackType: string,
      maxEstimateExpenses: number,
    },
  },
  modalUpdateListAction: {
    flag: string,
    cashbackId: any,
    isConfirmation: boolean,
    isLoading: boolean,
    isSuccess: boolean,
    isError: boolean,
    errorMessage: string,
    successMessage: string,
  },
  modalDownloadCashback: {
    isOpen: boolean,
    isLoading: boolean,
    data: any,
  },
  quota: {
    total: number,
    couponId: number,
    isError: boolean,
    isLoading: boolean,
    isSuccess: boolean,
    maxEstimateExpenses: number,
    isModalOpen: boolean,
    amount: number,
  },
  params: {
    page: number,
    limit: number,
    search: string,
    status: string,
    type: string,
    target: string,
    cashbackType: string,
  },
};
